version: '3.1'

services:
  multiple_datasource_service:
    container_name: multiple_datasource_service
    image: multiple_datasource_service
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - postgresqldb
      - postgresqldb2

  postgresqldb:
    image: postgres:13
    container_name: postgrsdb_container
    ports:
      - "5438:5432"
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgrs_db_multiple_connection

  postgresqldb2:
    image: postgres:13
    container_name: postgrsdb2_container
    ports:
      - "5439:5432"
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgrs_db_multiple_connection_2

volumes:
  postgres_data:
    driver: local
  postgres_data2:
    driver: local

